# Generated by Django 3.2.9 on 2021-11-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0002_auto_20211102_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.CharField(default='', max_length=8),
        ),
    ]
